#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v4
# autospec commit: f4bef72
#
Name     : quassel
Version  : 0.14.0
Release  : 13
URL      : https://github.com/quassel/quassel/archive/0.14.0/quassel-0.14.0.tar.gz
Source0  : https://github.com/quassel/quassel/archive/0.14.0/quassel-0.14.0.tar.gz
Source1  : quassel.tmpfiles
Source2  : quasselcore.service
Summary  : GoogleMock (without main() function)
Group    : Development/Tools
License  : BSD-3-Clause LGPL-2.1 LGPL-3.0
Requires: quassel-bin = %{version}-%{release}
Requires: quassel-config = %{version}-%{release}
Requires: quassel-data = %{version}-%{release}
Requires: quassel-lib = %{version}-%{release}
Requires: quassel-license = %{version}-%{release}
BuildRequires : boost-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules-data
BuildRequires : git
BuildRequires : glibc-dev
BuildRequires : googletest-dev
BuildRequires : mesa-dev
BuildRequires : phonon-dev
BuildRequires : pkgconfig(Qt6Core)
BuildRequires : pkgconfig(Qt6Multimedia)
BuildRequires : pkgconfig(libdrm)
BuildRequires : python3
BuildRequires : qtbase-dev
BuildRequires : qtbase-dev mesa-dev
BuildRequires : qtmultimedia-dev
BuildRequires : qttools-dev
BuildRequires : qtwebengine-dev
BuildRequires : sonnet-dev
BuildRequires : zlib-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
We bundle some CMake scripts that are not part of CMake itself, for convenience
on platforms that do not have a standard location for packages to put their
CMake support into. Most of those scripts originate from the KDE community;
some are from other sources. Please see the files themselves for copyright
and license statements.

%package bin
Summary: bin components for the quassel package.
Group: Binaries
Requires: quassel-data = %{version}-%{release}
Requires: quassel-config = %{version}-%{release}
Requires: quassel-license = %{version}-%{release}

%description bin
bin components for the quassel package.


%package config
Summary: config components for the quassel package.
Group: Default

%description config
config components for the quassel package.


%package data
Summary: data components for the quassel package.
Group: Data

%description data
data components for the quassel package.


%package dev
Summary: dev components for the quassel package.
Group: Development
Requires: quassel-lib = %{version}-%{release}
Requires: quassel-bin = %{version}-%{release}
Requires: quassel-data = %{version}-%{release}
Provides: quassel-devel = %{version}-%{release}
Requires: quassel = %{version}-%{release}

%description dev
dev components for the quassel package.


%package extras
Summary: extras components for the quassel package.
Group: Default

%description extras
extras components for the quassel package.


%package lib
Summary: lib components for the quassel package.
Group: Libraries
Requires: quassel-data = %{version}-%{release}
Requires: quassel-license = %{version}-%{release}

%description lib
lib components for the quassel package.


%package license
Summary: license components for the quassel package.
Group: Default

%description license
license components for the quassel package.


%prep
%setup -q -n quassel-0.14.0
cd %{_builddir}/quassel-0.14.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1710601677
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..
make  %{?_smp_mflags}
popd
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1710601677
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/quassel
cp %{_builddir}/quassel-%{version}/3rdparty/googletest-1.8.1/LICENSE %{buildroot}/usr/share/package-licenses/quassel/5a2314153eadadc69258a9429104cd11804ea304 || :
cp %{_builddir}/quassel-%{version}/3rdparty/googletest-1.8.1/googlemock/LICENSE %{buildroot}/usr/share/package-licenses/quassel/5a2314153eadadc69258a9429104cd11804ea304 || :
cp %{_builddir}/quassel-%{version}/3rdparty/googletest-1.8.1/googletest/LICENSE %{buildroot}/usr/share/package-licenses/quassel/5a2314153eadadc69258a9429104cd11804ea304 || :
cp %{_builddir}/quassel-%{version}/3rdparty/icons/breeze-dark/COPYING-ICONS %{buildroot}/usr/share/package-licenses/quassel/64474638fded94568edef3950d35b464488065b5 || :
cp %{_builddir}/quassel-%{version}/3rdparty/icons/breeze-dark/LICENSE %{buildroot}/usr/share/package-licenses/quassel/f45ee1c765646813b442ca58de72e20a64a7ddba || :
cp %{_builddir}/quassel-%{version}/3rdparty/icons/breeze/COPYING-ICONS %{buildroot}/usr/share/package-licenses/quassel/64474638fded94568edef3950d35b464488065b5 || :
cp %{_builddir}/quassel-%{version}/3rdparty/icons/breeze/LICENSE %{buildroot}/usr/share/package-licenses/quassel/f45ee1c765646813b442ca58de72e20a64a7ddba || :
cp %{_builddir}/quassel-%{version}/3rdparty/icons/oxygen/COPYING %{buildroot}/usr/share/package-licenses/quassel/d4ca5d36d06f97622e54feed256d8bff1c07db4d || :
cp %{_builddir}/quassel-%{version}/cmake/COPYING-CMAKE-SCRIPTS %{buildroot}/usr/share/package-licenses/quassel/d631f6b11ea65b2b02297d5a4bf1fc66885995d4 || :
export GOAMD64=v2
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 %{SOURCE2} %{buildroot}/usr/lib/systemd/system/quasselcore.service
mkdir -p %{buildroot}/usr/lib/tmpfiles.d
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/tmpfiles.d/quassel.conf
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/quassel
/V3/usr/bin/quasselclient
/usr/bin/quassel
/usr/bin/quasselclient

%files config
%defattr(-,root,root,-)
/usr/lib/tmpfiles.d/quassel.conf

%files data
%defattr(-,root,root,-)
/usr/share/applications/quassel.desktop
/usr/share/applications/quasselclient.desktop
/usr/share/icons/hicolor/128x128/apps/quassel.png
/usr/share/icons/hicolor/16x16/apps/quassel.png
/usr/share/icons/hicolor/22x22/apps/quassel.png
/usr/share/icons/hicolor/32x32/apps/quassel.png
/usr/share/icons/hicolor/48x48/apps/quassel.png
/usr/share/icons/hicolor/64x64/apps/quassel.png
/usr/share/quassel/icons/breeze-dark/AUTHORS
/usr/share/quassel/icons/breeze-dark/COPYING-ICONS
/usr/share/quassel/icons/breeze-dark/LICENSE
/usr/share/quassel/icons/breeze-dark/actions/16/application-exit.svg
/usr/share/quassel/icons/breeze-dark/actions/16/configure-shortcuts.svg
/usr/share/quassel/icons/breeze-dark/actions/16/configure.svg
/usr/share/quassel/icons/breeze-dark/actions/16/dialog-cancel.svg
/usr/share/quassel/icons/breeze-dark/actions/16/dialog-close.svg
/usr/share/quassel/icons/breeze-dark/actions/16/document-edit.svg
/usr/share/quassel/icons/breeze-dark/actions/16/document-encrypt.svg
/usr/share/quassel/icons/breeze-dark/actions/16/document-open.svg
/usr/share/quassel/icons/breeze-dark/actions/16/download.svg
/usr/share/quassel/icons/breeze-dark/actions/16/edit-clear-locationbar-ltr.svg
/usr/share/quassel/icons/breeze-dark/actions/16/edit-clear-locationbar-rtl.svg
/usr/share/quassel/icons/breeze-dark/actions/16/edit-clear.svg
/usr/share/quassel/icons/breeze-dark/actions/16/edit-copy.svg
/usr/share/quassel/icons/breeze-dark/actions/16/edit-delete.svg
/usr/share/quassel/icons/breeze-dark/actions/16/edit-find.svg
/usr/share/quassel/icons/breeze-dark/actions/16/edit-rename.svg
/usr/share/quassel/icons/breeze-dark/actions/16/flag-blue.svg
/usr/share/quassel/icons/breeze-dark/actions/16/format-fill-color.svg
/usr/share/quassel/icons/breeze-dark/actions/16/format-list-unordered.svg
/usr/share/quassel/icons/breeze-dark/actions/16/format-text-bold.svg
/usr/share/quassel/icons/breeze-dark/actions/16/format-text-color.svg
/usr/share/quassel/icons/breeze-dark/actions/16/format-text-italic.svg
/usr/share/quassel/icons/breeze-dark/actions/16/format-text-strikethrough.svg
/usr/share/quassel/icons/breeze-dark/actions/16/format-text-underline.svg
/usr/share/quassel/icons/breeze-dark/actions/16/go-down.svg
/usr/share/quassel/icons/breeze-dark/actions/16/go-next-view.svg
/usr/share/quassel/icons/breeze-dark/actions/16/go-next.svg
/usr/share/quassel/icons/breeze-dark/actions/16/go-previous-view.svg
/usr/share/quassel/icons/breeze-dark/actions/16/go-previous.svg
/usr/share/quassel/icons/breeze-dark/actions/16/go-up.svg
/usr/share/quassel/icons/breeze-dark/actions/16/help-about.svg
/usr/share/quassel/icons/breeze-dark/actions/16/im-ban-kick-user.svg
/usr/share/quassel/icons/breeze-dark/actions/16/im-ban-user.svg
/usr/share/quassel/icons/breeze-dark/actions/16/im-kick-user.svg
/usr/share/quassel/icons/breeze-dark/actions/16/im-user-away.svg
/usr/share/quassel/icons/breeze-dark/actions/16/im-user-offline.svg
/usr/share/quassel/icons/breeze-dark/actions/16/im-user-online.svg
/usr/share/quassel/icons/breeze-dark/actions/16/im-user.svg
/usr/share/quassel/icons/breeze-dark/actions/16/irc-channel-active.svg
/usr/share/quassel/icons/breeze-dark/actions/16/irc-channel-inactive.svg
/usr/share/quassel/icons/breeze-dark/actions/16/irc-close-channel.svg
/usr/share/quassel/icons/breeze-dark/actions/16/irc-join-channel.svg
/usr/share/quassel/icons/breeze-dark/actions/16/list-add-user.svg
/usr/share/quassel/icons/breeze-dark/actions/16/list-add.svg
/usr/share/quassel/icons/breeze-dark/actions/16/list-remove-user.svg
/usr/share/quassel/icons/breeze-dark/actions/16/mail-message-new.svg
/usr/share/quassel/icons/breeze-dark/actions/16/media-playback-start.svg
/usr/share/quassel/icons/breeze-dark/actions/16/network-connect.svg
/usr/share/quassel/icons/breeze-dark/actions/16/network-disconnect.svg
/usr/share/quassel/icons/breeze-dark/actions/16/show-menu.svg
/usr/share/quassel/icons/breeze-dark/actions/16/tools-report-bug.svg
/usr/share/quassel/icons/breeze-dark/actions/16/view-fullscreen.svg
/usr/share/quassel/icons/breeze-dark/actions/16/view-refresh.svg
/usr/share/quassel/icons/breeze-dark/actions/16/zoom-in.svg
/usr/share/quassel/icons/breeze-dark/actions/16/zoom-original.svg
/usr/share/quassel/icons/breeze-dark/actions/16/zoom-out.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/application-exit.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/configure-shortcuts.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/configure.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/dialog-cancel.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/dialog-close.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/document-edit.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/document-encrypt.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/document-open.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/download.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/edit-clear-locationbar-ltr.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/edit-clear-locationbar-rtl.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/edit-clear.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/edit-copy.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/edit-delete.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/edit-find.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/edit-rename.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/flag-blue.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/format-fill-color.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/format-list-unordered.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/format-text-bold.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/format-text-color.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/format-text-italic.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/format-text-strikethrough.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/format-text-underline.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/go-down.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/go-next-view.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/go-next.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/go-previous-view.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/go-previous.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/go-up.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/help-about.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/im-ban-kick-user.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/im-ban-user.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/im-kick-user.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/im-user-away.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/im-user-offline.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/im-user-online.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/im-user.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/irc-channel-active.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/irc-channel-inactive.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/irc-close-channel.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/irc-join-channel.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/list-add-user.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/list-add.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/list-remove-user.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/mail-message-new.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/media-playback-start.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/network-connect.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/network-disconnect.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/show-menu.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/tools-report-bug.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/view-fullscreen.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/view-refresh.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/zoom-in.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/zoom-original.svg
/usr/share/quassel/icons/breeze-dark/actions/16@2x/zoom-out.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/application-exit.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/configure-shortcuts.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/configure.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/dialog-cancel.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/dialog-close.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/document-edit.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/document-encrypt.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/document-open.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/download.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/edit-clear-locationbar-ltr.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/edit-clear-locationbar-rtl.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/edit-clear.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/edit-copy.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/edit-delete.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/edit-find.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/edit-rename.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/flag-blue.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/format-fill-color.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/format-list-unordered.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/format-text-bold.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/format-text-color.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/format-text-italic.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/format-text-strikethrough.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/format-text-underline.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/go-down.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/go-next-view.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/go-next.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/go-previous-view.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/go-previous.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/go-up.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/help-about.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/im-ban-kick-user.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/im-ban-user.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/im-kick-user.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/im-user-away.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/im-user-offline.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/im-user-online.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/im-user.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/irc-channel-active.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/irc-channel-inactive.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/irc-close-channel.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/irc-join-channel.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/list-add-user.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/list-add.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/list-remove-user.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/mail-message-new.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/media-playback-start.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/network-connect.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/network-disconnect.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/show-menu.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/tools-report-bug.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/view-fullscreen.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/view-refresh.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/zoom-in.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/zoom-original.svg
/usr/share/quassel/icons/breeze-dark/actions/16@3x/zoom-out.svg
/usr/share/quassel/icons/breeze-dark/actions/22/application-exit.svg
/usr/share/quassel/icons/breeze-dark/actions/22/configure-shortcuts.svg
/usr/share/quassel/icons/breeze-dark/actions/22/configure.svg
/usr/share/quassel/icons/breeze-dark/actions/22/dialog-cancel.svg
/usr/share/quassel/icons/breeze-dark/actions/22/dialog-close.svg
/usr/share/quassel/icons/breeze-dark/actions/22/document-edit.svg
/usr/share/quassel/icons/breeze-dark/actions/22/document-encrypt.svg
/usr/share/quassel/icons/breeze-dark/actions/22/document-open.svg
/usr/share/quassel/icons/breeze-dark/actions/22/download.svg
/usr/share/quassel/icons/breeze-dark/actions/22/edit-clear-locationbar-ltr.svg
/usr/share/quassel/icons/breeze-dark/actions/22/edit-clear-locationbar-rtl.svg
/usr/share/quassel/icons/breeze-dark/actions/22/edit-clear.svg
/usr/share/quassel/icons/breeze-dark/actions/22/edit-copy.svg
/usr/share/quassel/icons/breeze-dark/actions/22/edit-delete.svg
/usr/share/quassel/icons/breeze-dark/actions/22/edit-find.svg
/usr/share/quassel/icons/breeze-dark/actions/22/edit-rename.svg
/usr/share/quassel/icons/breeze-dark/actions/22/flag-blue.svg
/usr/share/quassel/icons/breeze-dark/actions/22/format-fill-color.svg
/usr/share/quassel/icons/breeze-dark/actions/22/format-list-unordered.svg
/usr/share/quassel/icons/breeze-dark/actions/22/format-text-bold.svg
/usr/share/quassel/icons/breeze-dark/actions/22/format-text-color.svg
/usr/share/quassel/icons/breeze-dark/actions/22/format-text-italic.svg
/usr/share/quassel/icons/breeze-dark/actions/22/format-text-strikethrough.svg
/usr/share/quassel/icons/breeze-dark/actions/22/format-text-underline.svg
/usr/share/quassel/icons/breeze-dark/actions/22/go-down.svg
/usr/share/quassel/icons/breeze-dark/actions/22/go-next-view.svg
/usr/share/quassel/icons/breeze-dark/actions/22/go-next.svg
/usr/share/quassel/icons/breeze-dark/actions/22/go-previous-view.svg
/usr/share/quassel/icons/breeze-dark/actions/22/go-previous.svg
/usr/share/quassel/icons/breeze-dark/actions/22/go-up.svg
/usr/share/quassel/icons/breeze-dark/actions/22/help-about.svg
/usr/share/quassel/icons/breeze-dark/actions/22/im-ban-kick-user.svg
/usr/share/quassel/icons/breeze-dark/actions/22/im-ban-user.svg
/usr/share/quassel/icons/breeze-dark/actions/22/im-kick-user.svg
/usr/share/quassel/icons/breeze-dark/actions/22/im-user-away.svg
/usr/share/quassel/icons/breeze-dark/actions/22/im-user-offline.svg
/usr/share/quassel/icons/breeze-dark/actions/22/im-user-online.svg
/usr/share/quassel/icons/breeze-dark/actions/22/im-user.svg
/usr/share/quassel/icons/breeze-dark/actions/22/irc-channel-active.svg
/usr/share/quassel/icons/breeze-dark/actions/22/irc-channel-inactive.svg
/usr/share/quassel/icons/breeze-dark/actions/22/irc-close-channel.svg
/usr/share/quassel/icons/breeze-dark/actions/22/irc-join-channel.svg
/usr/share/quassel/icons/breeze-dark/actions/22/irc-operator.svg
/usr/share/quassel/icons/breeze-dark/actions/22/irc-remove-operator.svg
/usr/share/quassel/icons/breeze-dark/actions/22/irc-unvoice.svg
/usr/share/quassel/icons/breeze-dark/actions/22/irc-voice.svg
/usr/share/quassel/icons/breeze-dark/actions/22/list-add-user.svg
/usr/share/quassel/icons/breeze-dark/actions/22/list-add.svg
/usr/share/quassel/icons/breeze-dark/actions/22/list-remove-user.svg
/usr/share/quassel/icons/breeze-dark/actions/22/mail-message-new.svg
/usr/share/quassel/icons/breeze-dark/actions/22/media-playback-start.svg
/usr/share/quassel/icons/breeze-dark/actions/22/network-connect.svg
/usr/share/quassel/icons/breeze-dark/actions/22/network-disconnect.svg
/usr/share/quassel/icons/breeze-dark/actions/22/show-menu.svg
/usr/share/quassel/icons/breeze-dark/actions/22/tools-report-bug.svg
/usr/share/quassel/icons/breeze-dark/actions/22/view-fullscreen.svg
/usr/share/quassel/icons/breeze-dark/actions/22/view-refresh.svg
/usr/share/quassel/icons/breeze-dark/actions/22/zoom-in.svg
/usr/share/quassel/icons/breeze-dark/actions/22/zoom-original.svg
/usr/share/quassel/icons/breeze-dark/actions/22/zoom-out.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/application-exit.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/configure-shortcuts.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/configure.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/dialog-cancel.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/dialog-close.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/document-edit.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/document-encrypt.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/document-open.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/download.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/edit-clear-locationbar-ltr.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/edit-clear-locationbar-rtl.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/edit-clear.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/edit-copy.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/edit-delete.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/edit-find.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/edit-rename.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/flag-blue.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/format-fill-color.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/format-list-unordered.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/format-text-bold.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/format-text-color.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/format-text-italic.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/format-text-strikethrough.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/format-text-underline.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/go-down.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/go-next-view.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/go-next.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/go-previous-view.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/go-previous.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/go-up.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/help-about.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/im-ban-kick-user.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/im-ban-user.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/im-kick-user.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/im-user-away.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/im-user-offline.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/im-user-online.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/im-user.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/irc-channel-active.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/irc-channel-inactive.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/irc-close-channel.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/irc-join-channel.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/irc-operator.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/irc-remove-operator.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/irc-unvoice.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/irc-voice.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/list-add-user.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/list-add.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/list-remove-user.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/mail-message-new.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/media-playback-start.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/network-connect.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/network-disconnect.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/show-menu.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/tools-report-bug.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/view-fullscreen.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/view-refresh.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/zoom-in.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/zoom-original.svg
/usr/share/quassel/icons/breeze-dark/actions/22@2x/zoom-out.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/application-exit.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/configure-shortcuts.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/configure.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/dialog-cancel.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/dialog-close.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/document-edit.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/document-encrypt.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/document-open.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/download.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/edit-clear-locationbar-ltr.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/edit-clear-locationbar-rtl.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/edit-clear.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/edit-copy.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/edit-delete.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/edit-find.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/edit-rename.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/flag-blue.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/format-fill-color.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/format-list-unordered.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/format-text-bold.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/format-text-color.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/format-text-italic.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/format-text-strikethrough.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/format-text-underline.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/go-down.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/go-next-view.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/go-next.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/go-previous-view.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/go-previous.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/go-up.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/help-about.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/im-ban-kick-user.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/im-ban-user.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/im-kick-user.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/im-user-away.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/im-user-offline.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/im-user-online.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/im-user.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/irc-channel-active.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/irc-channel-inactive.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/irc-close-channel.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/irc-join-channel.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/irc-operator.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/irc-remove-operator.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/irc-unvoice.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/irc-voice.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/list-add-user.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/list-add.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/list-remove-user.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/mail-message-new.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/media-playback-start.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/network-connect.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/network-disconnect.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/show-menu.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/tools-report-bug.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/view-fullscreen.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/view-refresh.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/zoom-in.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/zoom-original.svg
/usr/share/quassel/icons/breeze-dark/actions/22@3x/zoom-out.svg
/usr/share/quassel/icons/breeze-dark/actions/24/connect-quassel.svg
/usr/share/quassel/icons/breeze-dark/actions/24/disconnect-quassel.svg
/usr/share/quassel/icons/breeze-dark/actions/32/application-exit.svg
/usr/share/quassel/icons/breeze-dark/actions/32/configure-shortcuts.svg
/usr/share/quassel/icons/breeze-dark/actions/32/configure.svg
/usr/share/quassel/icons/breeze-dark/actions/32/connect-quassel.svg
/usr/share/quassel/icons/breeze-dark/actions/32/dialog-cancel.svg
/usr/share/quassel/icons/breeze-dark/actions/32/disconnect-quassel.svg
/usr/share/quassel/icons/breeze-dark/actions/32/document-edit.svg
/usr/share/quassel/icons/breeze-dark/actions/32/document-open.svg
/usr/share/quassel/icons/breeze-dark/actions/32/edit-delete.svg
/usr/share/quassel/icons/breeze-dark/actions/32/go-down.svg
/usr/share/quassel/icons/breeze-dark/actions/32/go-next.svg
/usr/share/quassel/icons/breeze-dark/actions/32/go-previous.svg
/usr/share/quassel/icons/breeze-dark/actions/32/go-up.svg
/usr/share/quassel/icons/breeze-dark/actions/32/help-about.svg
/usr/share/quassel/icons/breeze-dark/actions/32/mail-message-new.svg
/usr/share/quassel/icons/breeze-dark/actions/32/media-playback-start.svg
/usr/share/quassel/icons/breeze-dark/actions/32/view-refresh.svg
/usr/share/quassel/icons/breeze-dark/actions/32/zoom-in.svg
/usr/share/quassel/icons/breeze-dark/actions/32/zoom-original.svg
/usr/share/quassel/icons/breeze-dark/actions/32/zoom-out.svg
/usr/share/quassel/icons/breeze-dark/actions/32@2x/application-exit.svg
/usr/share/quassel/icons/breeze-dark/actions/32@2x/configure-shortcuts.svg
/usr/share/quassel/icons/breeze-dark/actions/32@2x/configure.svg
/usr/share/quassel/icons/breeze-dark/actions/32@2x/dialog-cancel.svg
/usr/share/quassel/icons/breeze-dark/actions/32@2x/document-edit.svg
/usr/share/quassel/icons/breeze-dark/actions/32@2x/document-open.svg
/usr/share/quassel/icons/breeze-dark/actions/32@2x/edit-delete.svg
/usr/share/quassel/icons/breeze-dark/actions/32@2x/go-down.svg
/usr/share/quassel/icons/breeze-dark/actions/32@2x/go-next.svg
/usr/share/quassel/icons/breeze-dark/actions/32@2x/go-previous.svg
/usr/share/quassel/icons/breeze-dark/actions/32@2x/go-up.svg
/usr/share/quassel/icons/breeze-dark/actions/32@2x/help-about.svg
/usr/share/quassel/icons/breeze-dark/actions/32@2x/mail-message-new.svg
/usr/share/quassel/icons/breeze-dark/actions/32@2x/media-playback-start.svg
/usr/share/quassel/icons/breeze-dark/actions/32@2x/view-refresh.svg
/usr/share/quassel/icons/breeze-dark/actions/32@2x/zoom-in.svg
/usr/share/quassel/icons/breeze-dark/actions/32@2x/zoom-original.svg
/usr/share/quassel/icons/breeze-dark/actions/32@2x/zoom-out.svg
/usr/share/quassel/icons/breeze-dark/actions/32@3x/application-exit.svg
/usr/share/quassel/icons/breeze-dark/actions/32@3x/configure-shortcuts.svg
/usr/share/quassel/icons/breeze-dark/actions/32@3x/configure.svg
/usr/share/quassel/icons/breeze-dark/actions/32@3x/dialog-cancel.svg
/usr/share/quassel/icons/breeze-dark/actions/32@3x/document-edit.svg
/usr/share/quassel/icons/breeze-dark/actions/32@3x/document-open.svg
/usr/share/quassel/icons/breeze-dark/actions/32@3x/edit-delete.svg
/usr/share/quassel/icons/breeze-dark/actions/32@3x/go-down.svg
/usr/share/quassel/icons/breeze-dark/actions/32@3x/go-next.svg
/usr/share/quassel/icons/breeze-dark/actions/32@3x/go-previous.svg
/usr/share/quassel/icons/breeze-dark/actions/32@3x/go-up.svg
/usr/share/quassel/icons/breeze-dark/actions/32@3x/help-about.svg
/usr/share/quassel/icons/breeze-dark/actions/32@3x/mail-message-new.svg
/usr/share/quassel/icons/breeze-dark/actions/32@3x/media-playback-start.svg
/usr/share/quassel/icons/breeze-dark/actions/32@3x/view-refresh.svg
/usr/share/quassel/icons/breeze-dark/actions/32@3x/zoom-in.svg
/usr/share/quassel/icons/breeze-dark/actions/32@3x/zoom-original.svg
/usr/share/quassel/icons/breeze-dark/actions/32@3x/zoom-out.svg
/usr/share/quassel/icons/breeze-dark/apps/32/quassel.svg
/usr/share/quassel/icons/breeze-dark/apps/48/quassel.svg
/usr/share/quassel/icons/breeze-dark/apps/64/quassel.svg
/usr/share/quassel/icons/breeze-dark/devices/16/network-wired.svg
/usr/share/quassel/icons/breeze-dark/devices/16@2x/network-wired.svg
/usr/share/quassel/icons/breeze-dark/devices/16@3x/network-wired.svg
/usr/share/quassel/icons/breeze-dark/devices/22/network-wired.svg
/usr/share/quassel/icons/breeze-dark/devices/22@2x/network-wired.svg
/usr/share/quassel/icons/breeze-dark/devices/22@3x/network-wired.svg
/usr/share/quassel/icons/breeze-dark/emblems/16/emblem-information.svg
/usr/share/quassel/icons/breeze-dark/emblems/16/emblem-question.svg
/usr/share/quassel/icons/breeze-dark/emblems/16/emblem-success.svg
/usr/share/quassel/icons/breeze-dark/emblems/16/emblem-unavailable.svg
/usr/share/quassel/icons/breeze-dark/emblems/16@2x/emblem-information.svg
/usr/share/quassel/icons/breeze-dark/emblems/16@2x/emblem-question.svg
/usr/share/quassel/icons/breeze-dark/emblems/16@2x/emblem-success.svg
/usr/share/quassel/icons/breeze-dark/emblems/16@2x/emblem-unavailable.svg
/usr/share/quassel/icons/breeze-dark/emblems/16@3x/emblem-information.svg
/usr/share/quassel/icons/breeze-dark/emblems/16@3x/emblem-question.svg
/usr/share/quassel/icons/breeze-dark/emblems/16@3x/emblem-success.svg
/usr/share/quassel/icons/breeze-dark/emblems/16@3x/emblem-unavailable.svg
/usr/share/quassel/icons/breeze-dark/emblems/22/emblem-information.svg
/usr/share/quassel/icons/breeze-dark/emblems/22/emblem-question.svg
/usr/share/quassel/icons/breeze-dark/emblems/22/emblem-success.svg
/usr/share/quassel/icons/breeze-dark/emblems/22/emblem-unavailable.svg
/usr/share/quassel/icons/breeze-dark/emblems/22@2x/emblem-information.svg
/usr/share/quassel/icons/breeze-dark/emblems/22@2x/emblem-question.svg
/usr/share/quassel/icons/breeze-dark/emblems/22@2x/emblem-success.svg
/usr/share/quassel/icons/breeze-dark/emblems/22@2x/emblem-unavailable.svg
/usr/share/quassel/icons/breeze-dark/emblems/22@3x/emblem-information.svg
/usr/share/quassel/icons/breeze-dark/emblems/22@3x/emblem-question.svg
/usr/share/quassel/icons/breeze-dark/emblems/22@3x/emblem-success.svg
/usr/share/quassel/icons/breeze-dark/emblems/22@3x/emblem-unavailable.svg
/usr/share/quassel/icons/breeze-dark/emblems/8/emblem-information.svg
/usr/share/quassel/icons/breeze-dark/emblems/8/emblem-question.svg
/usr/share/quassel/icons/breeze-dark/emblems/8/emblem-success.svg
/usr/share/quassel/icons/breeze-dark/emblems/8/emblem-unavailable.svg
/usr/share/quassel/icons/breeze-dark/index.theme
/usr/share/quassel/icons/breeze-dark/scalable/actions/connect-quassel.svg
/usr/share/quassel/icons/breeze-dark/scalable/actions/disconnect-quassel.svg
/usr/share/quassel/icons/breeze-dark/scalable/apps/quassel.svg
/usr/share/quassel/icons/breeze-dark/scalable/status/active-quassel-tray-inverted.svg
/usr/share/quassel/icons/breeze-dark/scalable/status/active-quassel-tray.svg
/usr/share/quassel/icons/breeze-dark/scalable/status/inactive-quassel-tray-inverted.svg
/usr/share/quassel/icons/breeze-dark/scalable/status/inactive-quassel-tray.svg
/usr/share/quassel/icons/breeze-dark/scalable/status/inactive-quassel.svg
/usr/share/quassel/icons/breeze-dark/scalable/status/message-quassel-tray-inverted.svg
/usr/share/quassel/icons/breeze-dark/scalable/status/message-quassel-tray.svg
/usr/share/quassel/icons/breeze-dark/scalable/status/message-quassel.svg
/usr/share/quassel/icons/breeze-dark/status/16/dialog-information.svg
/usr/share/quassel/icons/breeze-dark/status/16/dialog-warning.svg
/usr/share/quassel/icons/breeze-dark/status/16/security-high.svg
/usr/share/quassel/icons/breeze-dark/status/16/security-low.svg
/usr/share/quassel/icons/breeze-dark/status/16/user-available.svg
/usr/share/quassel/icons/breeze-dark/status/16/user-away.svg
/usr/share/quassel/icons/breeze-dark/status/16/user-offline.svg
/usr/share/quassel/icons/breeze-dark/status/16@2x/dialog-information.svg
/usr/share/quassel/icons/breeze-dark/status/16@2x/dialog-warning.svg
/usr/share/quassel/icons/breeze-dark/status/16@2x/security-high.svg
/usr/share/quassel/icons/breeze-dark/status/16@2x/security-low.svg
/usr/share/quassel/icons/breeze-dark/status/16@2x/user-available.svg
/usr/share/quassel/icons/breeze-dark/status/16@2x/user-away.svg
/usr/share/quassel/icons/breeze-dark/status/16@2x/user-offline.svg
/usr/share/quassel/icons/breeze-dark/status/16@3x/dialog-information.svg
/usr/share/quassel/icons/breeze-dark/status/16@3x/dialog-warning.svg
/usr/share/quassel/icons/breeze-dark/status/16@3x/security-high.svg
/usr/share/quassel/icons/breeze-dark/status/16@3x/security-low.svg
/usr/share/quassel/icons/breeze-dark/status/16@3x/user-available.svg
/usr/share/quassel/icons/breeze-dark/status/16@3x/user-away.svg
/usr/share/quassel/icons/breeze-dark/status/16@3x/user-offline.svg
/usr/share/quassel/icons/breeze-dark/status/22/dialog-information.svg
/usr/share/quassel/icons/breeze-dark/status/22/dialog-password.svg
/usr/share/quassel/icons/breeze-dark/status/22/dialog-warning.svg
/usr/share/quassel/icons/breeze-dark/status/22/security-high.svg
/usr/share/quassel/icons/breeze-dark/status/22/security-low.svg
/usr/share/quassel/icons/breeze-dark/status/22/user-available.svg
/usr/share/quassel/icons/breeze-dark/status/22/user-away.svg
/usr/share/quassel/icons/breeze-dark/status/22/user-offline.svg
/usr/share/quassel/icons/breeze-dark/status/22@2x/dialog-information.svg
/usr/share/quassel/icons/breeze-dark/status/22@2x/dialog-password.svg
/usr/share/quassel/icons/breeze-dark/status/22@2x/dialog-warning.svg
/usr/share/quassel/icons/breeze-dark/status/22@2x/security-high.svg
/usr/share/quassel/icons/breeze-dark/status/22@2x/security-low.svg
/usr/share/quassel/icons/breeze-dark/status/22@2x/user-available.svg
/usr/share/quassel/icons/breeze-dark/status/22@2x/user-away.svg
/usr/share/quassel/icons/breeze-dark/status/22@2x/user-offline.svg
/usr/share/quassel/icons/breeze-dark/status/22@3x/dialog-information.svg
/usr/share/quassel/icons/breeze-dark/status/22@3x/dialog-password.svg
/usr/share/quassel/icons/breeze-dark/status/22@3x/dialog-warning.svg
/usr/share/quassel/icons/breeze-dark/status/22@3x/security-high.svg
/usr/share/quassel/icons/breeze-dark/status/22@3x/security-low.svg
/usr/share/quassel/icons/breeze-dark/status/22@3x/user-available.svg
/usr/share/quassel/icons/breeze-dark/status/22@3x/user-away.svg
/usr/share/quassel/icons/breeze-dark/status/22@3x/user-offline.svg
/usr/share/quassel/icons/breeze-dark/status/24/active-quassel-tray-inverted.svg
/usr/share/quassel/icons/breeze-dark/status/24/active-quassel-tray.svg
/usr/share/quassel/icons/breeze-dark/status/24/inactive-quassel-tray-inverted.svg
/usr/share/quassel/icons/breeze-dark/status/24/inactive-quassel-tray.svg
/usr/share/quassel/icons/breeze-dark/status/24/inactive-quassel.svg
/usr/share/quassel/icons/breeze-dark/status/24/message-quassel-tray-inverted.svg
/usr/share/quassel/icons/breeze-dark/status/24/message-quassel-tray.svg
/usr/share/quassel/icons/breeze-dark/status/24/message-quassel.svg
/usr/share/quassel/icons/breeze-dark/status/32/dialog-warning.svg
/usr/share/quassel/icons/breeze-dark/status/48/dialog-warning.svg
/usr/share/quassel/icons/breeze-dark/status/64/active-quassel-tray-inverted.svg
/usr/share/quassel/icons/breeze-dark/status/64/active-quassel-tray.svg
/usr/share/quassel/icons/breeze-dark/status/64/dialog-information.svg
/usr/share/quassel/icons/breeze-dark/status/64/dialog-password.svg
/usr/share/quassel/icons/breeze-dark/status/64/dialog-warning.svg
/usr/share/quassel/icons/breeze-dark/status/64/inactive-quassel-tray-inverted.svg
/usr/share/quassel/icons/breeze-dark/status/64/inactive-quassel-tray.svg
/usr/share/quassel/icons/breeze-dark/status/64/inactive-quassel.svg
/usr/share/quassel/icons/breeze-dark/status/64/message-quassel-tray-inverted.svg
/usr/share/quassel/icons/breeze-dark/status/64/message-quassel-tray.svg
/usr/share/quassel/icons/breeze-dark/status/64/message-quassel.svg
/usr/share/quassel/icons/breeze-dark/status/64/security-high.svg
/usr/share/quassel/icons/breeze-dark/status/64/security-low.svg
/usr/share/quassel/icons/breeze/AUTHORS
/usr/share/quassel/icons/breeze/COPYING-ICONS
/usr/share/quassel/icons/breeze/LICENSE
/usr/share/quassel/icons/breeze/actions/16/application-exit.svg
/usr/share/quassel/icons/breeze/actions/16/configure-shortcuts.svg
/usr/share/quassel/icons/breeze/actions/16/configure.svg
/usr/share/quassel/icons/breeze/actions/16/dialog-cancel.svg
/usr/share/quassel/icons/breeze/actions/16/dialog-close.svg
/usr/share/quassel/icons/breeze/actions/16/document-edit.svg
/usr/share/quassel/icons/breeze/actions/16/document-encrypt.svg
/usr/share/quassel/icons/breeze/actions/16/document-open.svg
/usr/share/quassel/icons/breeze/actions/16/download.svg
/usr/share/quassel/icons/breeze/actions/16/edit-clear-locationbar-ltr.svg
/usr/share/quassel/icons/breeze/actions/16/edit-clear-locationbar-rtl.svg
/usr/share/quassel/icons/breeze/actions/16/edit-clear.svg
/usr/share/quassel/icons/breeze/actions/16/edit-copy.svg
/usr/share/quassel/icons/breeze/actions/16/edit-delete.svg
/usr/share/quassel/icons/breeze/actions/16/edit-find.svg
/usr/share/quassel/icons/breeze/actions/16/edit-rename.svg
/usr/share/quassel/icons/breeze/actions/16/flag-blue.svg
/usr/share/quassel/icons/breeze/actions/16/format-fill-color.svg
/usr/share/quassel/icons/breeze/actions/16/format-list-unordered.svg
/usr/share/quassel/icons/breeze/actions/16/format-text-bold.svg
/usr/share/quassel/icons/breeze/actions/16/format-text-color.svg
/usr/share/quassel/icons/breeze/actions/16/format-text-italic.svg
/usr/share/quassel/icons/breeze/actions/16/format-text-strikethrough.svg
/usr/share/quassel/icons/breeze/actions/16/format-text-underline.svg
/usr/share/quassel/icons/breeze/actions/16/go-down.svg
/usr/share/quassel/icons/breeze/actions/16/go-next-view.svg
/usr/share/quassel/icons/breeze/actions/16/go-next.svg
/usr/share/quassel/icons/breeze/actions/16/go-previous-view.svg
/usr/share/quassel/icons/breeze/actions/16/go-previous.svg
/usr/share/quassel/icons/breeze/actions/16/go-up.svg
/usr/share/quassel/icons/breeze/actions/16/help-about.svg
/usr/share/quassel/icons/breeze/actions/16/im-ban-kick-user.svg
/usr/share/quassel/icons/breeze/actions/16/im-ban-user.svg
/usr/share/quassel/icons/breeze/actions/16/im-kick-user.svg
/usr/share/quassel/icons/breeze/actions/16/im-user-away.svg
/usr/share/quassel/icons/breeze/actions/16/im-user-offline.svg
/usr/share/quassel/icons/breeze/actions/16/im-user-online.svg
/usr/share/quassel/icons/breeze/actions/16/im-user.svg
/usr/share/quassel/icons/breeze/actions/16/irc-channel-active.svg
/usr/share/quassel/icons/breeze/actions/16/irc-channel-inactive.svg
/usr/share/quassel/icons/breeze/actions/16/irc-close-channel.svg
/usr/share/quassel/icons/breeze/actions/16/irc-join-channel.svg
/usr/share/quassel/icons/breeze/actions/16/list-add-user.svg
/usr/share/quassel/icons/breeze/actions/16/list-add.svg
/usr/share/quassel/icons/breeze/actions/16/list-remove-user.svg
/usr/share/quassel/icons/breeze/actions/16/mail-message-new.svg
/usr/share/quassel/icons/breeze/actions/16/media-playback-start.svg
/usr/share/quassel/icons/breeze/actions/16/network-connect.svg
/usr/share/quassel/icons/breeze/actions/16/network-disconnect.svg
/usr/share/quassel/icons/breeze/actions/16/show-menu.svg
/usr/share/quassel/icons/breeze/actions/16/tools-report-bug.svg
/usr/share/quassel/icons/breeze/actions/16/view-fullscreen.svg
/usr/share/quassel/icons/breeze/actions/16/view-refresh.svg
/usr/share/quassel/icons/breeze/actions/16/zoom-in.svg
/usr/share/quassel/icons/breeze/actions/16/zoom-original.svg
/usr/share/quassel/icons/breeze/actions/16/zoom-out.svg
/usr/share/quassel/icons/breeze/actions/16@2x/application-exit.svg
/usr/share/quassel/icons/breeze/actions/16@2x/configure-shortcuts.svg
/usr/share/quassel/icons/breeze/actions/16@2x/configure.svg
/usr/share/quassel/icons/breeze/actions/16@2x/dialog-cancel.svg
/usr/share/quassel/icons/breeze/actions/16@2x/dialog-close.svg
/usr/share/quassel/icons/breeze/actions/16@2x/document-edit.svg
/usr/share/quassel/icons/breeze/actions/16@2x/document-encrypt.svg
/usr/share/quassel/icons/breeze/actions/16@2x/document-open.svg
/usr/share/quassel/icons/breeze/actions/16@2x/download.svg
/usr/share/quassel/icons/breeze/actions/16@2x/edit-clear-locationbar-ltr.svg
/usr/share/quassel/icons/breeze/actions/16@2x/edit-clear-locationbar-rtl.svg
/usr/share/quassel/icons/breeze/actions/16@2x/edit-clear.svg
/usr/share/quassel/icons/breeze/actions/16@2x/edit-copy.svg
/usr/share/quassel/icons/breeze/actions/16@2x/edit-delete.svg
/usr/share/quassel/icons/breeze/actions/16@2x/edit-find.svg
/usr/share/quassel/icons/breeze/actions/16@2x/edit-rename.svg
/usr/share/quassel/icons/breeze/actions/16@2x/flag-blue.svg
/usr/share/quassel/icons/breeze/actions/16@2x/format-fill-color.svg
/usr/share/quassel/icons/breeze/actions/16@2x/format-list-unordered.svg
/usr/share/quassel/icons/breeze/actions/16@2x/format-text-bold.svg
/usr/share/quassel/icons/breeze/actions/16@2x/format-text-color.svg
/usr/share/quassel/icons/breeze/actions/16@2x/format-text-italic.svg
/usr/share/quassel/icons/breeze/actions/16@2x/format-text-strikethrough.svg
/usr/share/quassel/icons/breeze/actions/16@2x/format-text-underline.svg
/usr/share/quassel/icons/breeze/actions/16@2x/go-down.svg
/usr/share/quassel/icons/breeze/actions/16@2x/go-next-view.svg
/usr/share/quassel/icons/breeze/actions/16@2x/go-next.svg
/usr/share/quassel/icons/breeze/actions/16@2x/go-previous-view.svg
/usr/share/quassel/icons/breeze/actions/16@2x/go-previous.svg
/usr/share/quassel/icons/breeze/actions/16@2x/go-up.svg
/usr/share/quassel/icons/breeze/actions/16@2x/help-about.svg
/usr/share/quassel/icons/breeze/actions/16@2x/im-ban-kick-user.svg
/usr/share/quassel/icons/breeze/actions/16@2x/im-ban-user.svg
/usr/share/quassel/icons/breeze/actions/16@2x/im-kick-user.svg
/usr/share/quassel/icons/breeze/actions/16@2x/im-user-away.svg
/usr/share/quassel/icons/breeze/actions/16@2x/im-user-offline.svg
/usr/share/quassel/icons/breeze/actions/16@2x/im-user-online.svg
/usr/share/quassel/icons/breeze/actions/16@2x/im-user.svg
/usr/share/quassel/icons/breeze/actions/16@2x/irc-channel-active.svg
/usr/share/quassel/icons/breeze/actions/16@2x/irc-channel-inactive.svg
/usr/share/quassel/icons/breeze/actions/16@2x/irc-close-channel.svg
/usr/share/quassel/icons/breeze/actions/16@2x/irc-join-channel.svg
/usr/share/quassel/icons/breeze/actions/16@2x/list-add-user.svg
/usr/share/quassel/icons/breeze/actions/16@2x/list-add.svg
/usr/share/quassel/icons/breeze/actions/16@2x/list-remove-user.svg
/usr/share/quassel/icons/breeze/actions/16@2x/mail-message-new.svg
/usr/share/quassel/icons/breeze/actions/16@2x/media-playback-start.svg
/usr/share/quassel/icons/breeze/actions/16@2x/network-connect.svg
/usr/share/quassel/icons/breeze/actions/16@2x/network-disconnect.svg
/usr/share/quassel/icons/breeze/actions/16@2x/show-menu.svg
/usr/share/quassel/icons/breeze/actions/16@2x/tools-report-bug.svg
/usr/share/quassel/icons/breeze/actions/16@2x/view-fullscreen.svg
/usr/share/quassel/icons/breeze/actions/16@2x/view-refresh.svg
/usr/share/quassel/icons/breeze/actions/16@2x/zoom-in.svg
/usr/share/quassel/icons/breeze/actions/16@2x/zoom-original.svg
/usr/share/quassel/icons/breeze/actions/16@2x/zoom-out.svg
/usr/share/quassel/icons/breeze/actions/16@3x/application-exit.svg
/usr/share/quassel/icons/breeze/actions/16@3x/configure-shortcuts.svg
/usr/share/quassel/icons/breeze/actions/16@3x/configure.svg
/usr/share/quassel/icons/breeze/actions/16@3x/dialog-cancel.svg
/usr/share/quassel/icons/breeze/actions/16@3x/dialog-close.svg
/usr/share/quassel/icons/breeze/actions/16@3x/document-edit.svg
/usr/share/quassel/icons/breeze/actions/16@3x/document-encrypt.svg
/usr/share/quassel/icons/breeze/actions/16@3x/document-open.svg
/usr/share/quassel/icons/breeze/actions/16@3x/download.svg
/usr/share/quassel/icons/breeze/actions/16@3x/edit-clear-locationbar-ltr.svg
/usr/share/quassel/icons/breeze/actions/16@3x/edit-clear-locationbar-rtl.svg
/usr/share/quassel/icons/breeze/actions/16@3x/edit-clear.svg
/usr/share/quassel/icons/breeze/actions/16@3x/edit-copy.svg
/usr/share/quassel/icons/breeze/actions/16@3x/edit-delete.svg
/usr/share/quassel/icons/breeze/actions/16@3x/edit-find.svg
/usr/share/quassel/icons/breeze/actions/16@3x/edit-rename.svg
/usr/share/quassel/icons/breeze/actions/16@3x/flag-blue.svg
/usr/share/quassel/icons/breeze/actions/16@3x/format-fill-color.svg
/usr/share/quassel/icons/breeze/actions/16@3x/format-list-unordered.svg
/usr/share/quassel/icons/breeze/actions/16@3x/format-text-bold.svg
/usr/share/quassel/icons/breeze/actions/16@3x/format-text-color.svg
/usr/share/quassel/icons/breeze/actions/16@3x/format-text-italic.svg
/usr/share/quassel/icons/breeze/actions/16@3x/format-text-strikethrough.svg
/usr/share/quassel/icons/breeze/actions/16@3x/format-text-underline.svg
/usr/share/quassel/icons/breeze/actions/16@3x/go-down.svg
/usr/share/quassel/icons/breeze/actions/16@3x/go-next-view.svg
/usr/share/quassel/icons/breeze/actions/16@3x/go-next.svg
/usr/share/quassel/icons/breeze/actions/16@3x/go-previous-view.svg
/usr/share/quassel/icons/breeze/actions/16@3x/go-previous.svg
/usr/share/quassel/icons/breeze/actions/16@3x/go-up.svg
/usr/share/quassel/icons/breeze/actions/16@3x/help-about.svg
/usr/share/quassel/icons/breeze/actions/16@3x/im-ban-kick-user.svg
/usr/share/quassel/icons/breeze/actions/16@3x/im-ban-user.svg
/usr/share/quassel/icons/breeze/actions/16@3x/im-kick-user.svg
/usr/share/quassel/icons/breeze/actions/16@3x/im-user-away.svg
/usr/share/quassel/icons/breeze/actions/16@3x/im-user-offline.svg
/usr/share/quassel/icons/breeze/actions/16@3x/im-user-online.svg
/usr/share/quassel/icons/breeze/actions/16@3x/im-user.svg
/usr/share/quassel/icons/breeze/actions/16@3x/irc-channel-active.svg
/usr/share/quassel/icons/breeze/actions/16@3x/irc-channel-inactive.svg
/usr/share/quassel/icons/breeze/actions/16@3x/irc-close-channel.svg
/usr/share/quassel/icons/breeze/actions/16@3x/irc-join-channel.svg
/usr/share/quassel/icons/breeze/actions/16@3x/list-add-user.svg
/usr/share/quassel/icons/breeze/actions/16@3x/list-add.svg
/usr/share/quassel/icons/breeze/actions/16@3x/list-remove-user.svg
/usr/share/quassel/icons/breeze/actions/16@3x/mail-message-new.svg
/usr/share/quassel/icons/breeze/actions/16@3x/media-playback-start.svg
/usr/share/quassel/icons/breeze/actions/16@3x/network-connect.svg
/usr/share/quassel/icons/breeze/actions/16@3x/network-disconnect.svg
/usr/share/quassel/icons/breeze/actions/16@3x/show-menu.svg
/usr/share/quassel/icons/breeze/actions/16@3x/tools-report-bug.svg
/usr/share/quassel/icons/breeze/actions/16@3x/view-fullscreen.svg
/usr/share/quassel/icons/breeze/actions/16@3x/view-refresh.svg
/usr/share/quassel/icons/breeze/actions/16@3x/zoom-in.svg
/usr/share/quassel/icons/breeze/actions/16@3x/zoom-original.svg
/usr/share/quassel/icons/breeze/actions/16@3x/zoom-out.svg
/usr/share/quassel/icons/breeze/actions/22/application-exit.svg
/usr/share/quassel/icons/breeze/actions/22/configure-shortcuts.svg
/usr/share/quassel/icons/breeze/actions/22/configure.svg
/usr/share/quassel/icons/breeze/actions/22/dialog-cancel.svg
/usr/share/quassel/icons/breeze/actions/22/dialog-close.svg
/usr/share/quassel/icons/breeze/actions/22/document-edit.svg
/usr/share/quassel/icons/breeze/actions/22/document-encrypt.svg
/usr/share/quassel/icons/breeze/actions/22/document-open.svg
/usr/share/quassel/icons/breeze/actions/22/download.svg
/usr/share/quassel/icons/breeze/actions/22/edit-clear-locationbar-ltr.svg
/usr/share/quassel/icons/breeze/actions/22/edit-clear-locationbar-rtl.svg
/usr/share/quassel/icons/breeze/actions/22/edit-clear.svg
/usr/share/quassel/icons/breeze/actions/22/edit-copy.svg
/usr/share/quassel/icons/breeze/actions/22/edit-delete.svg
/usr/share/quassel/icons/breeze/actions/22/edit-find.svg
/usr/share/quassel/icons/breeze/actions/22/edit-rename.svg
/usr/share/quassel/icons/breeze/actions/22/flag-blue.svg
/usr/share/quassel/icons/breeze/actions/22/format-fill-color.svg
/usr/share/quassel/icons/breeze/actions/22/format-list-unordered.svg
/usr/share/quassel/icons/breeze/actions/22/format-text-bold.svg
/usr/share/quassel/icons/breeze/actions/22/format-text-color.svg
/usr/share/quassel/icons/breeze/actions/22/format-text-italic.svg
/usr/share/quassel/icons/breeze/actions/22/format-text-strikethrough.svg
/usr/share/quassel/icons/breeze/actions/22/format-text-underline.svg
/usr/share/quassel/icons/breeze/actions/22/go-down.svg
/usr/share/quassel/icons/breeze/actions/22/go-next-view.svg
/usr/share/quassel/icons/breeze/actions/22/go-next.svg
/usr/share/quassel/icons/breeze/actions/22/go-previous-view.svg
/usr/share/quassel/icons/breeze/actions/22/go-previous.svg
/usr/share/quassel/icons/breeze/actions/22/go-up.svg
/usr/share/quassel/icons/breeze/actions/22/help-about.svg
/usr/share/quassel/icons/breeze/actions/22/im-ban-kick-user.svg
/usr/share/quassel/icons/breeze/actions/22/im-ban-user.svg
/usr/share/quassel/icons/breeze/actions/22/im-kick-user.svg
/usr/share/quassel/icons/breeze/actions/22/im-user-away.svg
/usr/share/quassel/icons/breeze/actions/22/im-user-offline.svg
/usr/share/quassel/icons/breeze/actions/22/im-user-online.svg
/usr/share/quassel/icons/breeze/actions/22/im-user.svg
/usr/share/quassel/icons/breeze/actions/22/irc-channel-active.svg
/usr/share/quassel/icons/breeze/actions/22/irc-channel-inactive.svg
/usr/share/quassel/icons/breeze/actions/22/irc-close-channel.svg
/usr/share/quassel/icons/breeze/actions/22/irc-join-channel.svg
/usr/share/quassel/icons/breeze/actions/22/irc-operator.svg
/usr/share/quassel/icons/breeze/actions/22/irc-remove-operator.svg
/usr/share/quassel/icons/breeze/actions/22/irc-unvoice.svg
/usr/share/quassel/icons/breeze/actions/22/irc-voice.svg
/usr/share/quassel/icons/breeze/actions/22/list-add-user.svg
/usr/share/quassel/icons/breeze/actions/22/list-add.svg
/usr/share/quassel/icons/breeze/actions/22/list-remove-user.svg
/usr/share/quassel/icons/breeze/actions/22/mail-message-new.svg
/usr/share/quassel/icons/breeze/actions/22/media-playback-start.svg
/usr/share/quassel/icons/breeze/actions/22/network-connect.svg
/usr/share/quassel/icons/breeze/actions/22/network-disconnect.svg
/usr/share/quassel/icons/breeze/actions/22/show-menu.svg
/usr/share/quassel/icons/breeze/actions/22/tools-report-bug.svg
/usr/share/quassel/icons/breeze/actions/22/view-fullscreen.svg
/usr/share/quassel/icons/breeze/actions/22/view-refresh.svg
/usr/share/quassel/icons/breeze/actions/22/zoom-in.svg
/usr/share/quassel/icons/breeze/actions/22/zoom-original.svg
/usr/share/quassel/icons/breeze/actions/22/zoom-out.svg
/usr/share/quassel/icons/breeze/actions/22@2x/application-exit.svg
/usr/share/quassel/icons/breeze/actions/22@2x/configure-shortcuts.svg
/usr/share/quassel/icons/breeze/actions/22@2x/configure.svg
/usr/share/quassel/icons/breeze/actions/22@2x/dialog-cancel.svg
/usr/share/quassel/icons/breeze/actions/22@2x/dialog-close.svg
/usr/share/quassel/icons/breeze/actions/22@2x/document-edit.svg
/usr/share/quassel/icons/breeze/actions/22@2x/document-encrypt.svg
/usr/share/quassel/icons/breeze/actions/22@2x/document-open.svg
/usr/share/quassel/icons/breeze/actions/22@2x/download.svg
/usr/share/quassel/icons/breeze/actions/22@2x/edit-clear-locationbar-ltr.svg
/usr/share/quassel/icons/breeze/actions/22@2x/edit-clear-locationbar-rtl.svg
/usr/share/quassel/icons/breeze/actions/22@2x/edit-clear.svg
/usr/share/quassel/icons/breeze/actions/22@2x/edit-copy.svg
/usr/share/quassel/icons/breeze/actions/22@2x/edit-delete.svg
/usr/share/quassel/icons/breeze/actions/22@2x/edit-find.svg
/usr/share/quassel/icons/breeze/actions/22@2x/edit-rename.svg
/usr/share/quassel/icons/breeze/actions/22@2x/flag-blue.svg
/usr/share/quassel/icons/breeze/actions/22@2x/format-fill-color.svg
/usr/share/quassel/icons/breeze/actions/22@2x/format-list-unordered.svg
/usr/share/quassel/icons/breeze/actions/22@2x/format-text-bold.svg
/usr/share/quassel/icons/breeze/actions/22@2x/format-text-color.svg
/usr/share/quassel/icons/breeze/actions/22@2x/format-text-italic.svg
/usr/share/quassel/icons/breeze/actions/22@2x/format-text-strikethrough.svg
/usr/share/quassel/icons/breeze/actions/22@2x/format-text-underline.svg
/usr/share/quassel/icons/breeze/actions/22@2x/go-down.svg
/usr/share/quassel/icons/breeze/actions/22@2x/go-next-view.svg
/usr/share/quassel/icons/breeze/actions/22@2x/go-next.svg
/usr/share/quassel/icons/breeze/actions/22@2x/go-previous-view.svg
/usr/share/quassel/icons/breeze/actions/22@2x/go-previous.svg
/usr/share/quassel/icons/breeze/actions/22@2x/go-up.svg
/usr/share/quassel/icons/breeze/actions/22@2x/help-about.svg
/usr/share/quassel/icons/breeze/actions/22@2x/im-ban-kick-user.svg
/usr/share/quassel/icons/breeze/actions/22@2x/im-ban-user.svg
/usr/share/quassel/icons/breeze/actions/22@2x/im-kick-user.svg
/usr/share/quassel/icons/breeze/actions/22@2x/im-user-away.svg
/usr/share/quassel/icons/breeze/actions/22@2x/im-user-offline.svg
/usr/share/quassel/icons/breeze/actions/22@2x/im-user-online.svg
/usr/share/quassel/icons/breeze/actions/22@2x/im-user.svg
/usr/share/quassel/icons/breeze/actions/22@2x/irc-channel-active.svg
/usr/share/quassel/icons/breeze/actions/22@2x/irc-channel-inactive.svg
/usr/share/quassel/icons/breeze/actions/22@2x/irc-close-channel.svg
/usr/share/quassel/icons/breeze/actions/22@2x/irc-join-channel.svg
/usr/share/quassel/icons/breeze/actions/22@2x/irc-operator.svg
/usr/share/quassel/icons/breeze/actions/22@2x/irc-remove-operator.svg
/usr/share/quassel/icons/breeze/actions/22@2x/irc-unvoice.svg
/usr/share/quassel/icons/breeze/actions/22@2x/irc-voice.svg
/usr/share/quassel/icons/breeze/actions/22@2x/list-add-user.svg
/usr/share/quassel/icons/breeze/actions/22@2x/list-add.svg
/usr/share/quassel/icons/breeze/actions/22@2x/list-remove-user.svg
/usr/share/quassel/icons/breeze/actions/22@2x/mail-message-new.svg
/usr/share/quassel/icons/breeze/actions/22@2x/media-playback-start.svg
/usr/share/quassel/icons/breeze/actions/22@2x/network-connect.svg
/usr/share/quassel/icons/breeze/actions/22@2x/network-disconnect.svg
/usr/share/quassel/icons/breeze/actions/22@2x/show-menu.svg
/usr/share/quassel/icons/breeze/actions/22@2x/tools-report-bug.svg
/usr/share/quassel/icons/breeze/actions/22@2x/view-fullscreen.svg
/usr/share/quassel/icons/breeze/actions/22@2x/view-refresh.svg
/usr/share/quassel/icons/breeze/actions/22@2x/zoom-in.svg
/usr/share/quassel/icons/breeze/actions/22@2x/zoom-original.svg
/usr/share/quassel/icons/breeze/actions/22@2x/zoom-out.svg
/usr/share/quassel/icons/breeze/actions/22@3x/application-exit.svg
/usr/share/quassel/icons/breeze/actions/22@3x/configure-shortcuts.svg
/usr/share/quassel/icons/breeze/actions/22@3x/configure.svg
/usr/share/quassel/icons/breeze/actions/22@3x/dialog-cancel.svg
/usr/share/quassel/icons/breeze/actions/22@3x/dialog-close.svg
/usr/share/quassel/icons/breeze/actions/22@3x/document-edit.svg
/usr/share/quassel/icons/breeze/actions/22@3x/document-encrypt.svg
/usr/share/quassel/icons/breeze/actions/22@3x/document-open.svg
/usr/share/quassel/icons/breeze/actions/22@3x/download.svg
/usr/share/quassel/icons/breeze/actions/22@3x/edit-clear-locationbar-ltr.svg
/usr/share/quassel/icons/breeze/actions/22@3x/edit-clear-locationbar-rtl.svg
/usr/share/quassel/icons/breeze/actions/22@3x/edit-clear.svg
/usr/share/quassel/icons/breeze/actions/22@3x/edit-copy.svg
/usr/share/quassel/icons/breeze/actions/22@3x/edit-delete.svg
/usr/share/quassel/icons/breeze/actions/22@3x/edit-find.svg
/usr/share/quassel/icons/breeze/actions/22@3x/edit-rename.svg
/usr/share/quassel/icons/breeze/actions/22@3x/flag-blue.svg
/usr/share/quassel/icons/breeze/actions/22@3x/format-fill-color.svg
/usr/share/quassel/icons/breeze/actions/22@3x/format-list-unordered.svg
/usr/share/quassel/icons/breeze/actions/22@3x/format-text-bold.svg
/usr/share/quassel/icons/breeze/actions/22@3x/format-text-color.svg
/usr/share/quassel/icons/breeze/actions/22@3x/format-text-italic.svg
/usr/share/quassel/icons/breeze/actions/22@3x/format-text-strikethrough.svg
/usr/share/quassel/icons/breeze/actions/22@3x/format-text-underline.svg
/usr/share/quassel/icons/breeze/actions/22@3x/go-down.svg
/usr/share/quassel/icons/breeze/actions/22@3x/go-next-view.svg
/usr/share/quassel/icons/breeze/actions/22@3x/go-next.svg
/usr/share/quassel/icons/breeze/actions/22@3x/go-previous-view.svg
/usr/share/quassel/icons/breeze/actions/22@3x/go-previous.svg
/usr/share/quassel/icons/breeze/actions/22@3x/go-up.svg
/usr/share/quassel/icons/breeze/actions/22@3x/help-about.svg
/usr/share/quassel/icons/breeze/actions/22@3x/im-ban-kick-user.svg
/usr/share/quassel/icons/breeze/actions/22@3x/im-ban-user.svg
/usr/share/quassel/icons/breeze/actions/22@3x/im-kick-user.svg
/usr/share/quassel/icons/breeze/actions/22@3x/im-user-away.svg
/usr/share/quassel/icons/breeze/actions/22@3x/im-user-offline.svg
/usr/share/quassel/icons/breeze/actions/22@3x/im-user-online.svg
/usr/share/quassel/icons/breeze/actions/22@3x/im-user.svg
/usr/share/quassel/icons/breeze/actions/22@3x/irc-channel-active.svg
/usr/share/quassel/icons/breeze/actions/22@3x/irc-channel-inactive.svg
/usr/share/quassel/icons/breeze/actions/22@3x/irc-close-channel.svg
/usr/share/quassel/icons/breeze/actions/22@3x/irc-join-channel.svg
/usr/share/quassel/icons/breeze/actions/22@3x/irc-operator.svg
/usr/share/quassel/icons/breeze/actions/22@3x/irc-remove-operator.svg
/usr/share/quassel/icons/breeze/actions/22@3x/irc-unvoice.svg
/usr/share/quassel/icons/breeze/actions/22@3x/irc-voice.svg
/usr/share/quassel/icons/breeze/actions/22@3x/list-add-user.svg
/usr/share/quassel/icons/breeze/actions/22@3x/list-add.svg
/usr/share/quassel/icons/breeze/actions/22@3x/list-remove-user.svg
/usr/share/quassel/icons/breeze/actions/22@3x/mail-message-new.svg
/usr/share/quassel/icons/breeze/actions/22@3x/media-playback-start.svg
/usr/share/quassel/icons/breeze/actions/22@3x/network-connect.svg
/usr/share/quassel/icons/breeze/actions/22@3x/network-disconnect.svg
/usr/share/quassel/icons/breeze/actions/22@3x/show-menu.svg
/usr/share/quassel/icons/breeze/actions/22@3x/tools-report-bug.svg
/usr/share/quassel/icons/breeze/actions/22@3x/view-fullscreen.svg
/usr/share/quassel/icons/breeze/actions/22@3x/view-refresh.svg
/usr/share/quassel/icons/breeze/actions/22@3x/zoom-in.svg
/usr/share/quassel/icons/breeze/actions/22@3x/zoom-original.svg
/usr/share/quassel/icons/breeze/actions/22@3x/zoom-out.svg
/usr/share/quassel/icons/breeze/actions/24/connect-quassel.svg
/usr/share/quassel/icons/breeze/actions/24/disconnect-quassel.svg
/usr/share/quassel/icons/breeze/actions/32/application-exit.svg
/usr/share/quassel/icons/breeze/actions/32/configure-shortcuts.svg
/usr/share/quassel/icons/breeze/actions/32/configure.svg
/usr/share/quassel/icons/breeze/actions/32/connect-quassel.svg
/usr/share/quassel/icons/breeze/actions/32/dialog-cancel.svg
/usr/share/quassel/icons/breeze/actions/32/disconnect-quassel.svg
/usr/share/quassel/icons/breeze/actions/32/document-edit.svg
/usr/share/quassel/icons/breeze/actions/32/document-open.svg
/usr/share/quassel/icons/breeze/actions/32/edit-delete.svg
/usr/share/quassel/icons/breeze/actions/32/go-down.svg
/usr/share/quassel/icons/breeze/actions/32/go-next.svg
/usr/share/quassel/icons/breeze/actions/32/go-previous.svg
/usr/share/quassel/icons/breeze/actions/32/go-up.svg
/usr/share/quassel/icons/breeze/actions/32/help-about.svg
/usr/share/quassel/icons/breeze/actions/32/mail-message-new.svg
/usr/share/quassel/icons/breeze/actions/32/media-playback-start.svg
/usr/share/quassel/icons/breeze/actions/32/view-refresh.svg
/usr/share/quassel/icons/breeze/actions/32/zoom-in.svg
/usr/share/quassel/icons/breeze/actions/32/zoom-original.svg
/usr/share/quassel/icons/breeze/actions/32/zoom-out.svg
/usr/share/quassel/icons/breeze/actions/32@2x/application-exit.svg
/usr/share/quassel/icons/breeze/actions/32@2x/configure-shortcuts.svg
/usr/share/quassel/icons/breeze/actions/32@2x/configure.svg
/usr/share/quassel/icons/breeze/actions/32@2x/dialog-cancel.svg
/usr/share/quassel/icons/breeze/actions/32@2x/document-edit.svg
/usr/share/quassel/icons/breeze/actions/32@2x/document-open.svg
/usr/share/quassel/icons/breeze/actions/32@2x/edit-delete.svg
/usr/share/quassel/icons/breeze/actions/32@2x/go-down.svg
/usr/share/quassel/icons/breeze/actions/32@2x/go-next.svg
/usr/share/quassel/icons/breeze/actions/32@2x/go-previous.svg
/usr/share/quassel/icons/breeze/actions/32@2x/go-up.svg
/usr/share/quassel/icons/breeze/actions/32@2x/help-about.svg
/usr/share/quassel/icons/breeze/actions/32@2x/mail-message-new.svg
/usr/share/quassel/icons/breeze/actions/32@2x/media-playback-start.svg
/usr/share/quassel/icons/breeze/actions/32@2x/view-refresh.svg
/usr/share/quassel/icons/breeze/actions/32@2x/zoom-in.svg
/usr/share/quassel/icons/breeze/actions/32@2x/zoom-original.svg
/usr/share/quassel/icons/breeze/actions/32@2x/zoom-out.svg
/usr/share/quassel/icons/breeze/actions/32@3x/application-exit.svg
/usr/share/quassel/icons/breeze/actions/32@3x/configure-shortcuts.svg
/usr/share/quassel/icons/breeze/actions/32@3x/configure.svg
/usr/share/quassel/icons/breeze/actions/32@3x/dialog-cancel.svg
/usr/share/quassel/icons/breeze/actions/32@3x/document-edit.svg
/usr/share/quassel/icons/breeze/actions/32@3x/document-open.svg
/usr/share/quassel/icons/breeze/actions/32@3x/edit-delete.svg
/usr/share/quassel/icons/breeze/actions/32@3x/go-down.svg
/usr/share/quassel/icons/breeze/actions/32@3x/go-next.svg
/usr/share/quassel/icons/breeze/actions/32@3x/go-previous.svg
/usr/share/quassel/icons/breeze/actions/32@3x/go-up.svg
/usr/share/quassel/icons/breeze/actions/32@3x/help-about.svg
/usr/share/quassel/icons/breeze/actions/32@3x/mail-message-new.svg
/usr/share/quassel/icons/breeze/actions/32@3x/media-playback-start.svg
/usr/share/quassel/icons/breeze/actions/32@3x/view-refresh.svg
/usr/share/quassel/icons/breeze/actions/32@3x/zoom-in.svg
/usr/share/quassel/icons/breeze/actions/32@3x/zoom-original.svg
/usr/share/quassel/icons/breeze/actions/32@3x/zoom-out.svg
/usr/share/quassel/icons/breeze/apps/32/quassel.svg
/usr/share/quassel/icons/breeze/apps/48/quassel.svg
/usr/share/quassel/icons/breeze/apps/64/quassel.svg
/usr/share/quassel/icons/breeze/devices/16/network-wired.svg
/usr/share/quassel/icons/breeze/devices/16@2x/network-wired.svg
/usr/share/quassel/icons/breeze/devices/16@3x/network-wired.svg
/usr/share/quassel/icons/breeze/devices/22/network-wired.svg
/usr/share/quassel/icons/breeze/devices/22@2x/network-wired.svg
/usr/share/quassel/icons/breeze/devices/22@3x/network-wired.svg
/usr/share/quassel/icons/breeze/emblems/16/emblem-information.svg
/usr/share/quassel/icons/breeze/emblems/16/emblem-question.svg
/usr/share/quassel/icons/breeze/emblems/16/emblem-success.svg
/usr/share/quassel/icons/breeze/emblems/16/emblem-unavailable.svg
/usr/share/quassel/icons/breeze/emblems/16@2x/emblem-information.svg
/usr/share/quassel/icons/breeze/emblems/16@2x/emblem-question.svg
/usr/share/quassel/icons/breeze/emblems/16@2x/emblem-success.svg
/usr/share/quassel/icons/breeze/emblems/16@2x/emblem-unavailable.svg
/usr/share/quassel/icons/breeze/emblems/16@3x/emblem-information.svg
/usr/share/quassel/icons/breeze/emblems/16@3x/emblem-question.svg
/usr/share/quassel/icons/breeze/emblems/16@3x/emblem-success.svg
/usr/share/quassel/icons/breeze/emblems/16@3x/emblem-unavailable.svg
/usr/share/quassel/icons/breeze/emblems/22/emblem-information.svg
/usr/share/quassel/icons/breeze/emblems/22/emblem-question.svg
/usr/share/quassel/icons/breeze/emblems/22/emblem-success.svg
/usr/share/quassel/icons/breeze/emblems/22/emblem-unavailable.svg
/usr/share/quassel/icons/breeze/emblems/22@2x/emblem-information.svg
/usr/share/quassel/icons/breeze/emblems/22@2x/emblem-question.svg
/usr/share/quassel/icons/breeze/emblems/22@2x/emblem-success.svg
/usr/share/quassel/icons/breeze/emblems/22@2x/emblem-unavailable.svg
/usr/share/quassel/icons/breeze/emblems/22@3x/emblem-information.svg
/usr/share/quassel/icons/breeze/emblems/22@3x/emblem-question.svg
/usr/share/quassel/icons/breeze/emblems/22@3x/emblem-success.svg
/usr/share/quassel/icons/breeze/emblems/22@3x/emblem-unavailable.svg
/usr/share/quassel/icons/breeze/emblems/8/emblem-information.svg
/usr/share/quassel/icons/breeze/emblems/8/emblem-question.svg
/usr/share/quassel/icons/breeze/emblems/8/emblem-success.svg
/usr/share/quassel/icons/breeze/emblems/8/emblem-unavailable.svg
/usr/share/quassel/icons/breeze/index.theme
/usr/share/quassel/icons/breeze/scalable/actions/connect-quassel.svg
/usr/share/quassel/icons/breeze/scalable/actions/disconnect-quassel.svg
/usr/share/quassel/icons/breeze/scalable/apps/quassel.svg
/usr/share/quassel/icons/breeze/scalable/status/active-quassel-tray-inverted.svg
/usr/share/quassel/icons/breeze/scalable/status/active-quassel-tray.svg
/usr/share/quassel/icons/breeze/scalable/status/inactive-quassel-tray-inverted.svg
/usr/share/quassel/icons/breeze/scalable/status/inactive-quassel-tray.svg
/usr/share/quassel/icons/breeze/scalable/status/inactive-quassel.svg
/usr/share/quassel/icons/breeze/scalable/status/message-quassel-tray-inverted.svg
/usr/share/quassel/icons/breeze/scalable/status/message-quassel-tray.svg
/usr/share/quassel/icons/breeze/scalable/status/message-quassel.svg
/usr/share/quassel/icons/breeze/status/16/dialog-information.svg
/usr/share/quassel/icons/breeze/status/16/dialog-warning.svg
/usr/share/quassel/icons/breeze/status/16/security-high.svg
/usr/share/quassel/icons/breeze/status/16/security-low.svg
/usr/share/quassel/icons/breeze/status/16/user-available.svg
/usr/share/quassel/icons/breeze/status/16/user-away.svg
/usr/share/quassel/icons/breeze/status/16/user-offline.svg
/usr/share/quassel/icons/breeze/status/16@2x/dialog-information.svg
/usr/share/quassel/icons/breeze/status/16@2x/dialog-warning.svg
/usr/share/quassel/icons/breeze/status/16@2x/security-high.svg
/usr/share/quassel/icons/breeze/status/16@2x/security-low.svg
/usr/share/quassel/icons/breeze/status/16@2x/user-available.svg
/usr/share/quassel/icons/breeze/status/16@2x/user-away.svg
/usr/share/quassel/icons/breeze/status/16@2x/user-offline.svg
/usr/share/quassel/icons/breeze/status/16@3x/dialog-information.svg
/usr/share/quassel/icons/breeze/status/16@3x/dialog-warning.svg
/usr/share/quassel/icons/breeze/status/16@3x/security-high.svg
/usr/share/quassel/icons/breeze/status/16@3x/security-low.svg
/usr/share/quassel/icons/breeze/status/16@3x/user-available.svg
/usr/share/quassel/icons/breeze/status/16@3x/user-away.svg
/usr/share/quassel/icons/breeze/status/16@3x/user-offline.svg
/usr/share/quassel/icons/breeze/status/22/dialog-information.svg
/usr/share/quassel/icons/breeze/status/22/dialog-password.svg
/usr/share/quassel/icons/breeze/status/22/dialog-warning.svg
/usr/share/quassel/icons/breeze/status/22/security-high.svg
/usr/share/quassel/icons/breeze/status/22/security-low.svg
/usr/share/quassel/icons/breeze/status/22/user-available.svg
/usr/share/quassel/icons/breeze/status/22/user-away.svg
/usr/share/quassel/icons/breeze/status/22/user-offline.svg
/usr/share/quassel/icons/breeze/status/22@2x/dialog-information.svg
/usr/share/quassel/icons/breeze/status/22@2x/dialog-password.svg
/usr/share/quassel/icons/breeze/status/22@2x/dialog-warning.svg
/usr/share/quassel/icons/breeze/status/22@2x/security-high.svg
/usr/share/quassel/icons/breeze/status/22@2x/security-low.svg
/usr/share/quassel/icons/breeze/status/22@2x/user-available.svg
/usr/share/quassel/icons/breeze/status/22@2x/user-away.svg
/usr/share/quassel/icons/breeze/status/22@2x/user-offline.svg
/usr/share/quassel/icons/breeze/status/22@3x/dialog-information.svg
/usr/share/quassel/icons/breeze/status/22@3x/dialog-password.svg
/usr/share/quassel/icons/breeze/status/22@3x/dialog-warning.svg
/usr/share/quassel/icons/breeze/status/22@3x/security-high.svg
/usr/share/quassel/icons/breeze/status/22@3x/security-low.svg
/usr/share/quassel/icons/breeze/status/22@3x/user-available.svg
/usr/share/quassel/icons/breeze/status/22@3x/user-away.svg
/usr/share/quassel/icons/breeze/status/22@3x/user-offline.svg
/usr/share/quassel/icons/breeze/status/24/active-quassel-tray-inverted.svg
/usr/share/quassel/icons/breeze/status/24/active-quassel-tray.svg
/usr/share/quassel/icons/breeze/status/24/inactive-quassel-tray-inverted.svg
/usr/share/quassel/icons/breeze/status/24/inactive-quassel-tray.svg
/usr/share/quassel/icons/breeze/status/24/inactive-quassel.svg
/usr/share/quassel/icons/breeze/status/24/message-quassel-tray-inverted.svg
/usr/share/quassel/icons/breeze/status/24/message-quassel-tray.svg
/usr/share/quassel/icons/breeze/status/24/message-quassel.svg
/usr/share/quassel/icons/breeze/status/32/dialog-warning.svg
/usr/share/quassel/icons/breeze/status/48/dialog-warning.svg
/usr/share/quassel/icons/breeze/status/64/active-quassel-tray-inverted.svg
/usr/share/quassel/icons/breeze/status/64/active-quassel-tray.svg
/usr/share/quassel/icons/breeze/status/64/dialog-information.svg
/usr/share/quassel/icons/breeze/status/64/dialog-password.svg
/usr/share/quassel/icons/breeze/status/64/dialog-warning.svg
/usr/share/quassel/icons/breeze/status/64/inactive-quassel-tray-inverted.svg
/usr/share/quassel/icons/breeze/status/64/inactive-quassel-tray.svg
/usr/share/quassel/icons/breeze/status/64/inactive-quassel.svg
/usr/share/quassel/icons/breeze/status/64/message-quassel-tray-inverted.svg
/usr/share/quassel/icons/breeze/status/64/message-quassel-tray.svg
/usr/share/quassel/icons/breeze/status/64/message-quassel.svg
/usr/share/quassel/icons/breeze/status/64/security-high.svg
/usr/share/quassel/icons/breeze/status/64/security-low.svg
/usr/share/quassel/networks.ini
/usr/share/quassel/scripts/inxi
/usr/share/quassel/scripts/mpris
/usr/share/quassel/stylesheets/DarkMonokai.qss
/usr/share/quassel/stylesheets/DarkSolarized.qss
/usr/share/quassel/stylesheets/LinuxDolt-bluestheme.qss
/usr/share/quassel/stylesheets/a3.qss
/usr/share/quassel/stylesheets/default.qss
/usr/share/quassel/stylesheets/elbryan_quassel_theme.qss
/usr/share/quassel/stylesheets/gabydewilde-black.qss
/usr/share/quassel/stylesheets/jussi01-darktheme.qss
/usr/share/quassel/stylesheets/m4yer.qss
/usr/share/quassel/stylesheets/mj12cyan.qss
/usr/share/quassel/stylesheets/qwater.qss
/usr/share/quassel/stylesheets/temerity1.0.1.qss
/usr/share/quassel/translations/cs.qm
/usr/share/quassel/translations/da.qm
/usr/share/quassel/translations/de.qm
/usr/share/quassel/translations/el.qm
/usr/share/quassel/translations/en_GB.qm
/usr/share/quassel/translations/en_US.qm
/usr/share/quassel/translations/eo.qm
/usr/share/quassel/translations/es.qm
/usr/share/quassel/translations/et.qm
/usr/share/quassel/translations/fi.qm
/usr/share/quassel/translations/fr.qm
/usr/share/quassel/translations/gl.qm
/usr/share/quassel/translations/hi.qm
/usr/share/quassel/translations/hu.qm
/usr/share/quassel/translations/it.qm
/usr/share/quassel/translations/ja.qm
/usr/share/quassel/translations/ko.qm
/usr/share/quassel/translations/lt.qm
/usr/share/quassel/translations/mr.qm
/usr/share/quassel/translations/nb.qm
/usr/share/quassel/translations/nl.qm
/usr/share/quassel/translations/oc.qm
/usr/share/quassel/translations/pa.qm
/usr/share/quassel/translations/pl.qm
/usr/share/quassel/translations/pt.qm
/usr/share/quassel/translations/pt_BR.qm
/usr/share/quassel/translations/ro.qm
/usr/share/quassel/translations/ru.qm
/usr/share/quassel/translations/sl.qm
/usr/share/quassel/translations/sq.qm
/usr/share/quassel/translations/sr.qm
/usr/share/quassel/translations/sv.qm
/usr/share/quassel/translations/tr.qm
/usr/share/quassel/translations/uk.qm
/usr/share/quassel/translations/zh_CN.qm

%files dev
%defattr(-,root,root,-)
/usr/lib64/libquassel-client.so
/usr/lib64/libquassel-common.so
/usr/lib64/libquassel-core.so
/usr/lib64/libquassel-qtui.so
/usr/lib64/libquassel-uisupport.so

%files extras
%defattr(-,root,root,-)
/V3/usr/bin/quasselcore
/usr/bin/quasselcore
/usr/lib/systemd/system/quasselcore.service

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libquassel-client.so.0.14.0
/V3/usr/lib64/libquassel-common.so.0.14.0
/V3/usr/lib64/libquassel-core.so.0.14.0
/V3/usr/lib64/libquassel-qtui.so.0.14.0
/V3/usr/lib64/libquassel-uisupport.so.0.14.0
/usr/lib64/libquassel-client.so.0.14.0
/usr/lib64/libquassel-common.so.0.14.0
/usr/lib64/libquassel-core.so.0.14.0
/usr/lib64/libquassel-qtui.so.0.14.0
/usr/lib64/libquassel-uisupport.so.0.14.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/quassel/5a2314153eadadc69258a9429104cd11804ea304
/usr/share/package-licenses/quassel/64474638fded94568edef3950d35b464488065b5
/usr/share/package-licenses/quassel/d4ca5d36d06f97622e54feed256d8bff1c07db4d
/usr/share/package-licenses/quassel/d631f6b11ea65b2b02297d5a4bf1fc66885995d4
/usr/share/package-licenses/quassel/f45ee1c765646813b442ca58de72e20a64a7ddba
